version: '3'

services:
  chat-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env
      - model_cache:/app/model_cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
volumes:
  model_cache:
    driver: local 